# Generated by Django 4.2.7 on 2024-01-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_app', '0002_image_content_type_image_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='image',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
    ]
