# Generated by Django 4.2.7 on 2024-01-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0001_initial'),
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='product_app.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ManyToManyField(to='vendor_app.vendor'),
        ),
    ]
