# Generated by Django 4.2.7 on 2024-01-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='product',
            name='videos',
        ),
    ]
