# Generated by Django 4.2.7 on 2024-01-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_remove_product_photos_remove_product_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
