# Generated by Django 4.2.7 on 2024-01-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_rename_sub_category_category_top_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='top_category',
        ),
        migrations.AddField(
            model_name='category',
            name='sub_category',
            field=models.ManyToManyField(blank=True, to='product_app.category'),
        ),
    ]
