# Generated by Django 4.2.7 on 2024-01-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, null=True, to='product_app.product'),
        ),
    ]
