# Generated by Django 4.2.7 on 2024-01-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0011_alter_category_managers_category_level_category_lft_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='expire_date',
            field=models.DateTimeField(null=True),
        ),
    ]
