# Generated by Django 4.2.7 on 2024-01-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0016_alter_product_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='django-db-models-fields-charfield', max_length=500, unique=True),
        ),
    ]
