# Generated by Django 4.2.7 on 2024-01-06 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
        ('shopping_cart_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartProductRelatations',
            new_name='CartProductRelation',
        ),
    ]
