# Generated by Django 4.2.7 on 2024-01-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart_app', '0002_rename_cartproductrelatations_cartproductrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproductrelation',
            name='amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
