# Generated by Django 4.2.7 on 2024-01-11 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproductrelation',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
