# Generated by Django 4.2.7 on 2024-01-07 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart_app', '0003_cartproductrelation_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproductrelation',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shopping_cart_app.cart'),
        ),
        migrations.AlterField(
            model_name='cartproductrelation',
            name='product',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
