# Generated by Django 4.2.7 on 2024-01-07 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
        ('shopping_cart_app', '0004_alter_cartproductrelation_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproductrelation',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.product'),
        ),
    ]
