# Generated by Django 4.2.7 on 2024-01-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart_app', '0005_alter_cartproductrelation_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproductrelation',
            name='product_cost',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
