# Generated by Django 4.2.7 on 2024-01-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_userpostrelation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostrelation',
            name='grade',
            field=models.IntegerField(choices=[(1, 1), (0, 0), (-1, -1)], default=0),
        ),
    ]
