# Generated by Django 4.2.7 on 2024-01-10 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_userpostrelation_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpostrelation',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='userpostrelation',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='userpostrelation',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='userpostrelation',
            name='user',
        ),
    ]
