# Generated by Django 4.2.7 on 2024-01-10 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user_app', '0006_remove_userpostrelation_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpostrelation',
            name='content_type_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='userpostrelation',
            name='grade',
            field=models.IntegerField(choices=[(1, 1), (0, 0), (-1, -1)], default=0),
        ),
        migrations.AddField(
            model_name='userpostrelation',
            name='object_id_1',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userpostrelation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
