# Generated by Django 4.2.7 on 2024-01-10 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_userpostrelation_content_type_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpostrelation',
            old_name='content_type_1',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='userpostrelation',
            old_name='object_id_1',
            new_name='object_id',
        ),
    ]
