# Generated by Django 4.2.7 on 2024-01-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_actions_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='Grade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
