# Generated by Django 4.2.7 on 2024-01-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_actions_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='photo',
        ),
    ]
