# Generated by Django 4.2.7 on 2024-01-09 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_actions_app', '0002_review_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Grade',
            new_name='grade',
        ),
    ]
