# Generated by Django 4.2.7 on 2024-01-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_actions_app', '0003_rename_grade_review_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.PositiveIntegerField(),
        ),
    ]
