# Generated by Django 4.2.7 on 2024-01-09 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_actions_app', '0005_alter_review_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepost',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.PositiveIntegerField(),
        ),
    ]
