# Generated by Django 4.2.7 on 2024-01-09 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_actions_app', '0006_alter_basepost_rating_alter_review_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepost',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
